// Code generated by mockery 2.7.4. DO NOT EDIT.

package manage

import (
	mock "github.com/stretchr/testify/mock"
	"yalochat.com/salesforce-integration/base/cache"
)

// ContextCache is an autogenerated mock type for the ContextCache type
type ContextCacheMock struct {
	mock.Mock
}

// RetrieveContext provides a mock function with given fields: userID
func (_m *ContextCacheMock) RetrieveContext(userID string) []cache.Context {
	ret := _m.Called(userID)

	var r0 []cache.Context
	if rf, ok := ret.Get(0).(func(string) []cache.Context); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]cache.Context)
		}
	}

	return r0
}

// StoreContext provides a mock function with given fields: _a0
func (_m *ContextCacheMock) StoreContext(_a0 cache.Context) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(cache.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
