image: golang:1.14

options:
  docker: true

definitions:
  steps:
    - step: &test
        name: Test
        script:
          - .yalo/utils/test-go.sh
        services: 
          - redis 
    - step: &push
        name: Push to Docker Hub
        script:
          - REPO=salesforce-integration .yalo/utils/build.sh
    - step: &push_release
        name: Push Release to Docker Hub
        script:
          - REPO=salesforce-integration BRANCH=release .yalo/utils/build.sh
  services: 
    redis: 
      image: redis

pipelines:
  default:
    - parallel:
      - step: *test
  branches: 
    develop:
      - parallel:
        - step: *test
        - step: *push
    master:
      - parallel:
        - step: *test
        - step: *push
    '{release/**,hotfix/**}':
      - parallel:
        - step: *test
        - step: *push_release        
  tags:
    '*.*.*':
      - step:
          name: deploy to staging
          deployment: staging
          script:
            - REPO=salesforce-integration .yalo/utils/deploy-staging.sh
      - step:
          name: deploy to production
          deployment: production
          trigger: manual
          script:
            - REPO=salesforce-integration .yalo/utils/deploy-prod.sh