package handlers

import (
	mock "github.com/stretchr/testify/mock"
	manage "yalochat.com/salesforce-integration/app/manage"

	models "yalochat.com/salesforce-integration/base/models"
)

// ManagerI is an autogenerated mock type for the ManagerI type
type ManagerI struct {
	mock.Mock
}

// CreateChat provides a mock function with given fields: interconnection
func (_m *ManagerI) CreateChat(interconnection *manage.Interconnection) error {
	ret := _m.Called(interconnection)

	var r0 error
	if rf, ok := ret.Get(0).(func(*manage.Interconnection) error); ok {
		r0 = rf(interconnection)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveContext provides a mock function with given fields: integration
func (_m *ManagerI) SaveContext(integration *models.IntegrationsRequest) error {
	ret := _m.Called(integration)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.IntegrationsRequest) error); ok {
		r0 = rf(integration)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetContextByUserID provides a mock function with given fields: userID
func (_m *ManagerI) GetContextByUserID(userID string) string {
	ret := _m.Called(userID)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
