// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	context "context"

	cache "yalochat.com/salesforce-integration/base/cache"

	manage "yalochat.com/salesforce-integration/app/manage"

	mock "github.com/stretchr/testify/mock"

	models "yalochat.com/salesforce-integration/base/models"
)

// ManagerI is an autogenerated mock type for the ManagerI type
type ManagerI struct {
	mock.Mock
}

// CreateChat provides a mock function with given fields: ctx, interconnection
func (_m *ManagerI) CreateChat(ctx context.Context, interconnection *manage.Interconnection) error {
	ret := _m.Called(ctx, interconnection)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *manage.Interconnection) error); ok {
		r0 = rf(ctx, interconnection)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FinishChat provides a mock function with given fields: userID
func (_m *ManagerI) FinishChat(userID string) error {
	ret := _m.Called(userID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetContextByUserID provides a mock function with given fields: userID
func (_m *ManagerI) GetContextByUserID(userID string) []cache.Context {
	ret := _m.Called(userID)

	var r0 []cache.Context
	if rf, ok := ret.Get(0).(func(string) []cache.Context); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]cache.Context)
		}
	}

	return r0
}

// RegisterWebhookInIntegrations provides a mock function with given fields: provider
func (_m *ManagerI) RegisterWebhookInIntegrations(provider string) error {
	ret := _m.Called(provider)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(provider)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveWebhookInIntegrations provides a mock function with given fields: provider
func (_m *ManagerI) RemoveWebhookInIntegrations(provider string) error {
	ret := _m.Called(provider)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(provider)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveContext provides a mock function with given fields: ctx, integration
func (_m *ManagerI) SaveContext(ctx context.Context, integration *models.IntegrationsRequest) error {
	ret := _m.Called(ctx, integration)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.IntegrationsRequest) error); ok {
		r0 = rf(ctx, integration)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveContextFB provides a mock function with given fields: ctx, integration
func (_m *ManagerI) SaveContextFB(ctx context.Context, integration *models.IntegrationsFacebook) error {
	ret := _m.Called(ctx, integration)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.IntegrationsFacebook) error); ok {
		r0 = rf(ctx, integration)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewManagerI interface {
	mock.TestingT
	Cleanup(func())
}

// NewManagerI creates a new instance of ManagerI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewManagerI(t mockConstructorTestingTNewManagerI) *ManagerI {
	mock := &ManagerI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
