// Code generated by mockery 2.7.4. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
	proxy "yalochat.com/salesforce-integration/base/clients/proxy"
)

// ProxyInterface is an autogenerated mock type for the ProxyInterface type
type ProxyInterface struct {
	mock.Mock
}

// SendHTTPRequest provides a mock function with given fields: request
func (_m *ProxyInterface) SendHTTPRequest(request *proxy.Request) (*http.Response, error) {
	ret := _m.Called(request)

	var r0 *http.Response
	if rf, ok := ret.Get(0).(func(*proxy.Request) *http.Response); ok {
		r0 = rf(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*proxy.Request) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
