// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// BotRunnerInterface is an autogenerated mock type for the BotRunnerInterface type
type BotRunnerInterface struct {
	mock.Mock
}

// SendTo provides a mock function with given fields: object
func (_m *BotRunnerInterface) SendTo(object map[string]interface{}) (bool, error) {
	ret := _m.Called(object)

	var r0 bool
	if rf, ok := ret.Get(0).(func(map[string]interface{}) bool); ok {
		r0 = rf(object)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(map[string]interface{}) error); ok {
		r1 = rf(object)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewBotRunnerInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewBotRunnerInterface creates a new instance of BotRunnerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewBotRunnerInterface(t mockConstructorTestingTNewBotRunnerInterface) *BotRunnerInterface {
	mock := &BotRunnerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
