// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// StudioNGInterface is an autogenerated mock type for the StudioNGInterface type
type StudioNGInterface struct {
	mock.Mock
}

// SendTo provides a mock function with given fields: state, userID
func (_m *StudioNGInterface) SendTo(state string, userID string) error {
	ret := _m.Called(state, userID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(state, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewStudioNGInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewStudioNGInterface creates a new instance of StudioNGInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewStudioNGInterface(t mockConstructorTestingTNewStudioNGInterface) *StudioNGInterface {
	mock := &StudioNGInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
