name: Deploy for production

on:
  push:
    tags:
      - v*.*.*

jobs:
  deploy_production:
    name: Build and push production image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Create GitHub token
        id: get_workflow_token
        uses: jnwng/github-app-installation-token-action@v2
        with:
          appId: ${{ secrets.READ_ONLY_GITHUB_APP_ID }}
          installationId: ${{ secrets.READ_ONLY_GITHUB_APP_INSTALLATION_ID }}
          privateKey: ${{ secrets.READ_ONLY_GITHUB_APP_PRIVATE_KEY }}

      - name: Build and publish docker image
        env:
          TAG: ${{github.ref_name}}
          GITHUB_TOKEN: ${{steps.get_workflow_token.outputs.token}}
        run: |
          export IMAGE_NAME=yalochat/${{ github.event.repository.name }}:${{github.ref_name}}
          docker build -t $IMAGE_NAME -f app/build/Dockerfile .
          docker push $IMAGE_NAME
