name: Quality Check

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - '**/*.md'

jobs:
  unit_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Install dependencies
        run: go mod download

      - name: Run Tests
        run: go test -test.count 1 -test.timeout 30s -coverprofile=./coverage.txt -v ./...

      - name: Upload Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
